Frontend/react-client/package-lock.json
Frontend/react-client/package.json
Frontend/react-client/src/App.tsx
Frontend/react-client/src/index.tsx
Frontend/react-client/src/pages/dashboard/Dashboard.tsx
Frontend/react-client/src/pages/visitor/Visitor.tsx

Add fluentui and reactrouter with sample showing that theyre working

Add fluentui and reactrouter

---

src/BffWeb/ClientApp/src/App.tsx
src/BffWeb/ClientApp/src/pages/home/home.tsx

We might want to add more infos in the future or a call to action button

Add homepage with basic infos

---

src/Core/Controllers/UserProfileController.cs
src/Core/Models/Estimation.cs
src/Core/Models/EstimationHandler.cs
src/Core/Models/IEstimationHandler.cs
src/Core/Models/ITagHandler.cs
src/Core/Models/Tag.cs
src/Core/Models/TagHandler.cs

Files for db structure and interaction

Add Database structure and Database interaction

---

src/BffWeb/ClientApp/src/components/navbar/default-navbar.tsx
src/BffWeb/ClientApp/src/helpers/routes.tsx
src/BffWeb/ClientApp/src/pages/settings/settings.tsx

We can add more options once we have established BFF / Core connection

Add settings page for bff claims

---

src/BffWeb/ClientApp/src/helpers/api.types.ts
src/BffWeb/ClientApp/src/helpers/estimations.ts
src/BffWeb/ClientApp/src/pages/dashboard/Dashboard.tsx
src/Core/Controllers/EstimationController.cs
src/Core/Services/EstimationService.cs
src/Core/Services/IEstimationService.cs

For testing purposes, we added an endpoint that gives back the result of a static user. This is only temporary so the frontend isn't blocked during development.
In the future this API will be reworked to return estimations of the current user

Add  static test endpoint for calling estimations

---

Docs/Draw.Io/ServerArchitecture.drawio

Update server architecture Docs with BFF

---

.gitignore
src/Core/PoseEstimation/estimate_pose.py
src/Core/PoseEstimation/vp3d_installer.ps1

- installer now uses a sub direction for vp3d so that the git clone works
- uses fork of detection which is python37 compatible
- add FFmpeg install for windows

Fix installer and missing ffmpeg

---

src/BffWeb/ClientApp/public/manifest.json
src/BffWeb/ClientApp/src/components/upload-button/upload-button.tsx
src/BffWeb/ClientApp/src/pages/dashboard/dashboard.tsx
src/BffWeb/Program.cs
src/Core/Controllers/AttachmentController.cs
src/Core/Controllers/UploadController.cs
src/Core/Models/Constants.cs
src/Core/Models/UploadModel.cs
src/Core/Services/EstimationService.cs
src/Core/Services/IEstimationService.cs

User can now use frontend FAB button to initiate a upload which has a few simple hints

Add estimation upload

---

src/BffWeb/ClientApp/src/components/estimation-list/estimation-list.tsx
src/BffWeb/ClientApp/src/components/estimation-view/estimation-view.tsx
src/BffWeb/ClientApp/src/components/upload-button/upload-button.tsx
src/BffWeb/ClientApp/src/helpers/api.types.ts
src/BffWeb/ClientApp/src/helpers/claims.ts
src/BffWeb/ClientApp/src/helpers/estimations.ts
src/BffWeb/ClientApp/src/pages/dashboard/dashboard.tsx
src/Core/Controllers/AttachmentController.cs
src/Core/Controllers/UploadController.cs
src/Core/Models/AttachmentType.cs
src/Core/Models/Constants.cs
src/Core/Models/Estimation.cs
src/Core/Models/EstimationState.cs
src/Core/Services/EstimationService.cs
src/Core/Services/QueueService.cs

- Added queuing with state indicating it
- Added json download of joint coordinates
- Add auto refetching
- Increase upload size to 50mb
- Fixes:
- incorrect attachment check
- crash during int parse

Implement fixes and features from test findings

---

Docs/Draw.Io/DatabaseStructure.drawio

add queued state
add .json estimation result attachment

updated db structure diagram

---

src/BffWeb/ClientApp/src/components/navbar/default-navbar.tsx
src/BffWeb/ClientApp/src/pages/home/home.tsx

One or two users had issues finding the login button. Made it now obviously that login is a requirement to use the app and made the login button itself more prominent

Make login buttons more obvious

---

src/BffWeb/ClientApp/package-lock.json
src/BffWeb/ClientApp/package.json
src/BffWeb/ClientApp/src/components/estimation-list/estimation-list.tsx
src/BffWeb/ClientApp/src/components/upload-button/upload-button.tsx
src/BffWeb/ClientApp/src/helpers/api.types.ts
src/Core/Services/EstimationService.cs
src/Core/Services/IEstimationService.cs

Made following adjustmens based on user feedback:
- improved error handling (exception is shown in frontend on error icon)
- less crashes
- fix time zone localization issue
- Make UI for file selection more clear
- Made state text readable for mobile

Implement user feedback

---

Docs/Draw.Io/DatabaseStructure.drawio

new Queue State
new field StateText
Typo fix

Update db diagramm

---

src/BffWeb/ClientApp/src/components/upload-button/upload-button.tsx
src/BffWeb/ClientApp/src/pages/dashboard/dashboard.tsx
src/BffWeb/Program.cs
src/Core/Controllers/UploadController.cs
src/Core/Program.cs

- added hint that only mp4 works
- increase endpoint max file size, previously a user couldn't upload anything bigger than 25mb

Improve upload behaviour

---

README.md

Add mocap preview to readme

---

src/BffWeb/ClientApp/src/components/estimation-view/estimation-view.tsx
src/BffWeb/ClientApp/src/helpers/api.types.ts
src/BffWeb/ClientApp/src/helpers/estimations.ts
src/Core/Controllers/AttachmentController.cs
src/Core/Models/AttachmentType.cs
src/Core/Models/Constants.cs
src/Core/PoseEstimation/bvh_skeleton/bvh_helper.py
src/Core/PoseEstimation/bvh_skeleton/h36m_skeleton.py
src/Core/PoseEstimation/bvh_skeleton/math3d.py
src/Core/PoseEstimation/estimate_pose.py
src/Core/PoseEstimation/output2bvh.py
src/Core/Services/EstimationService.cs

Added new python script which creates a bvh file after a successful estimation

Add support for motion capture data

---

src/Core/FbxGeneration/bvh2fbx.py

Added bones for right collar, left collar and lower back.
This makes retargeting easier for most use cases

Add additonal bones for FBX

---

src/Core/FbxGeneration/bvh2fbx.py

1.9 rotation looks the best for VideoPose3d outputs

Fix rotation for FBX

---

src/Core/FbxGeneration/bvh2fbx.py
src/Core/Models/AttachmentType.cs
src/Core/Models/Constants.cs
src/Core/PoseEstimation/estimate_pose.py
src/Core/Services/Estimations/EstimationService.cs

- Added initial TPose frame FBX and BVH -> used for retargeting in blender
- Fixed fbx rotation for it to look good

Improve animations for retargeting and viewing

---

src/Core/Models/EstimatorConfig.cs
src/Core/Services/Estimations/EstimationService.cs
src/Core/Services/Fbx/FbxService.cs
src/Core/Services/Fbx/IFbxService.cs

A good start to support multiple pose estimators

Add config for multiple estimators
